### ISSUE TITLE
As a user, I can top up my wallet

### ISSUE THREAD

**Issue by iwle** [cs2102team20/cs2102team20-crowd-funding-frontend#10]
`/profile/{id}/topup_wallet`

- [x] ~The user shall be able to top up the wallet's credit on the profile page using valid credit card information. (ITERATION 1)~ [We are simply allowing them to increase the amount int their wallets (not worrying about actual money in our app)]
- [x] Credit on the wallet must not be lower than the total amount pledged for all the projects backed. (ITERATION 1)

**Comment by ptvrajsk** [comment]
Can the URL of the wallet page be `/profile/wallet/`. Then URL of Top Up be `profile/wallet/topup` ? Cause theres no need for wallet here, since we're implementing Vuex store we can simply store who the user is (email address) and use the identity to query for data.

**Comment by ptvrajsk** [comment]
@iwle 

How's this for a basic wallet page?
Do we need any thing else added?

<img width="1440" alt="wallet" src="https://user-images.githubusercontent.com/39243082/67452510-0996aa00-f656-11e9-96b1-5def866f4ae2.png">
